### ISSUE TITLE
Change Type recipe now shows a Kotlin example only

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#211]
Would have expected a Java example at least, not only Kotlin.
https://docs.openrewrite.org/recipes/java/changetype

**Comment by timtebeek** [comment]
@kunli2 / @mike-solomon not sure if this is in the right repository, or who of you would best know how to resolve this.

**Comment by mike-solomon** [comment]
I suspect this is probably going to require a change in the markdown generator and that Kun would have the background for this. I haven’t looked at the auto generated test stuff.

**Comment by mike-solomon** [comment]
I took a look into this and I'm wondering if the Groovy stuff is perhaps conflicting with the Java stuff. For instance, I see that the `ChangeType` recipe is using this test: https://github.com/openrewrite/rewrite/blob/5d1cb3cecd4e3abccdc77410d407192a732d0a7b/rewrite-groovy/src/test/java/org/openrewrite/groovy/ChangeTypeAdaptabilityTest.java#L98-L108

instead of the one I'd expect here: https://github.com/openrewrite/rewrite/blob/main/rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java#L64-L65

It also is somehow getting a path of `file.kt`, but I don't see where that is coming from.

**Comment by timtebeek** [comment]
I think it's even this test that's picked up, since the docs mention Kotlin:
https://github.com/openrewrite/rewrite-kotlin/blob/678acef1b7d656e8df75e1bedd7c4c6b7cb497ca/src/test/java/org/openrewrite/kotlin/ChangeTypeTest.java#L149-L151

Is there anyway to disambiguate which one gets shown in the docs @kunli2 ?

**Comment by mike-solomon** [comment]
Ah good find @timtebeek that makes more sense.

**Comment by kunli2** [comment]
Seems the plug-in doesn't work on the `rewrite` repo, so the java example yaml file was generated as expected from `rewrite`.
however, the plug-in works for other repos.
I'll look into this issue.

**Comment by kunli2** [comment]
I have verified that, after bumping the `rewrite` version in the plug-in (https://github.com/openrewrite/rewrite-build-gradle-plugin/commit/e034bfdb2cc56074d9731cbc1ec3a5fcaf8b7640), the parsing error in `rewrite` is fixed.
Will release `rewrite-build-gradle-plugin` and rewrite will automatically pick up the latest plug-in and missing java examples will be back

**Comment by kunli2** [comment]
Hi @mike-solomon, do we want to update the doc or wait until the next rewrite release (nothing needs to do)?

**Comment by mike-solomon** [comment]
@kunli2 I just tried re-generating the docs just now and I still see the Java Change Type recipe showing Kotlin code. Does something else need to happen for these changes to appear?

**Comment by kunli2** [comment]
I think that's because the rewrite didn't pick up the latest `rewrite-build-gradle-plugin` 1.12.1 but 1.12.0.
you can do this in your local to force pick up the 1.12.1

```diff
diff --git a/build.gradle.kts b/build.gradle.kts
index eddf8702a..85038a402 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -1,6 +1,6 @@
 plugins {
-    id("org.openrewrite.build.root") version("latest.release")
-    id("org.openrewrite.build.java-base") version("latest.release")
+    id("org.openrewrite.build.root") version("1.12.1")
+    id("org.openrewrite.build.java-base") version("1.12.1")
     id("org.openrewrite.rewrite") version("latest.release")
 }
```

**Comment by mike-solomon** [comment]
After making the changes, I haven't been able to get the expected results locally. Kun is going to try and run the markdown generator on his machine and see if it works for him.

**Comment by mike-solomon** [comment]
This should be resolved once the next version of OpenRewrite is released and we re-generate the docs. Leaving as blocked until the next release happens.

**Comment by mike-solomon** [comment]
@kunli2 I re-generated the docs today and `ChangeType` now no longer has any example associated with it. I remember last week it was mentioned that the example code was slowing down builds. I'm guessing no recipes will have examples anymore right now?

**Comment by timtebeek** [comment]
I'd noticed https://github.com/openrewrite/rewrite-build-gradle-plugin/commit/dec3f046e56d03f4dd7a8f12813ec7f1e3ddeb14 just now; that'll factor in. Not clear yet why or how to resolve, but figured share it here such you at least know.

**Comment by timtebeek** [comment]
I've just logged https://github.com/openrewrite/rewrite-build-gradle-plugin/issues/20 to track why the examples aren't extracted right now.

**Comment by mike-solomon** [comment]
As this is similar to [this issue](https://github.com/openrewrite/rewrite-docs/issues/210) and as that issue is probably not going to be resolved anytime soon, I'm going to close this. If examples are ever produced again for the docs, we can come back and ensure that Kotlin ones work appropriately.
